"""
polyphony.cli.cmd_practice
==========================
Offline-first practice workflow for training new users safely.
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm
from rich.table import Table

from ..db import connect, insert, json_col, project_db_path, write_project_marker
from ..generators import generate_llm_data, generate_template_data, get_domains
from ..io.importers import import_documents
from ..utils import slugify

console = Console()


_DEFAULT_PRACTICE_RQS = [
    "How can we use polyphony's coding workflow reliably?",
    "Which themes are easiest and hardest to code consistently?",
]


def _create_practice_project(
    conn,
    *,
    name: str,
    slug: str,
    methodology: str,
    model_a: str,
    model_b: str,
    temperature: float,
) -> int:
    """Create a minimal project scaffold for practice use."""
    project_id = insert(conn, "project", {
        "name": name,
        "slug": slug,
        "description": "Practice sandbox generated by `polyphony practice`.",
        "methodology": methodology,
        "research_questions": json_col(_DEFAULT_PRACTICE_RQS),
        "status": "setup",
        "config": json.dumps({"practice": True}, ensure_ascii=False),
    })

    insert(conn, "agent", {
        "project_id": project_id,
        "role": "supervisor",
        "agent_type": "human",
        "model_name": "human",
        "model_version": "human",
        "temperature": 0.0,
        "seed": 0,
        "system_prompt": "Human supervisor",
    })

    insert(conn, "agent", {
        "project_id": project_id,
        "role": "coder_a",
        "agent_type": "llm",
        "model_name": model_a,
        "model_version": "unknown",
        "temperature": temperature,
        "seed": 42,
        "system_prompt": None,
    })

    insert(conn, "agent", {
        "project_id": project_id,
        "role": "coder_b",
        "agent_type": "llm",
        "model_name": model_b,
        "model_version": "unknown",
        "temperature": temperature,
        "seed": 137,
        "system_prompt": None,
    })

    conn.commit()
    return project_id


def _import_generated_segments(
    conn,
    *,
    project_id: int,
    project_dir: Path,
    generated_segments: list[dict],
) -> dict:
    """Persist generated segments via the existing importer path."""
    payload = [
        {
            "content": segment.get("text", ""),
            "metadata": segment.get("metadata", {}),
        }
        for segment in generated_segments
        if segment.get("text", "").strip()
    ]

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".json",
        delete=False,
        encoding="utf-8",
    ) as tmp:
        json.dump(payload, tmp, ensure_ascii=False, indent=2)
        temp_path = Path(tmp.name)

    try:
        return import_documents(
            conn=conn,
            project_id=project_id,
            paths=[temp_path],
            segment_strategy="manual",
            project_dir=project_dir,
        )
    finally:
        temp_path.unlink(missing_ok=True)


def _print_suggested_codes(codes: list[dict]) -> None:
    if not codes:
        return

    table = Table(title="Suggested Starter Codes", show_header=True)
    table.add_column("Code", style="cyan")
    table.add_column("Description")

    for code in codes:
        table.add_row(code.get("name", ""), code.get("description", ""))

    console.print(table)


@click.command()
@click.option("--name", default="Practice Sandbox", show_default=True,
              help="Practice project name.")
@click.option("--slug", default="practice-sandbox", show_default=True,
              help="Practice project slug.")
@click.option(
    "--methodology",
    type=click.Choice(["grounded_theory", "thematic_analysis", "content_analysis"]),
    default="grounded_theory",
    show_default=True,
    help="QDA methodology for the practice project.",
)
@click.option("--model-a", default="llama3.1:8b", show_default=True,
              help="Configured model for Coder A (used when you run coding).")
@click.option("--model-b", default="llama3.1:8b", show_default=True,
              help="Configured model for Coder B (used when you run coding).")
@click.option("--temperature", default=0.1, show_default=True,
              type=click.FloatRange(0.0, 1.0), help="Saved coder temperature config.")
@click.option("--domain", default="housing", show_default=True,
              help="Offline synthetic domain (used when --topic/--source-file are not set).")
@click.option("--segments", default=20, show_default=True,
              type=click.IntRange(1, 500), help="Number of synthetic segments to generate.")
@click.option("--seed", default=42, show_default=True,
              type=int, help="Seed for synthetic generation.")
@click.option("--topic", default=None,
              help="Optional topic for LLM-generated synthetic data (requires Ollama).")
@click.option("--llm-model", default="llama3.2", show_default=True,
              help="Ollama model for --topic mode.")
@click.option(
    "--source-file",
    "source_files",
    multiple=True,
    type=click.Path(path_type=Path, exists=True),
    help="Optional real data file(s) to import into sandbox instead of generating synthetic data.",
)
@click.option(
    "--segment-by",
    default="paragraph",
    show_default=True,
    help="Segmentation strategy for --source-file imports.",
)
@click.option("--list-domains", is_flag=True,
              help="List available offline synthetic domains and exit.")
@click.option("--overwrite", is_flag=True,
              help="Overwrite existing practice project without confirmation prompt.")
@click.option("--no-open", is_flag=True,
              help="Do not write .polyphony_project in the current directory.")
@click.pass_context
def practice(
    ctx: click.Context,
    name: str,
    slug: str,
    methodology: str,
    model_a: str,
    model_b: str,
    temperature: float,
    domain: str,
    segments: int,
    seed: int,
    topic: str | None,
    llm_model: str,
    source_files: tuple[Path, ...],
    segment_by: str,
    list_domains: bool,
    overwrite: bool,
    no_open: bool,
) -> None:
    """Create a sandbox project and load practice data.

    Default mode is fully offline using template-generated synthetic data.
    """
    domains = get_domains()
    if list_domains:
        table = Table(title="Practice Domains", show_header=True)
        table.add_column("Key", style="cyan")
        table.add_column("Description")
        for key, description in domains.items():
            table.add_row(key, description)
        console.print(table)
        return

    if source_files and topic:
        console.print("[red]Choose either --source-file or --topic, not both.[/]")
        sys.exit(1)

    if domain not in domains:
        console.print(
            f"[red]Unknown domain '{domain}'.[/] "
            "Use [bold]polyphony practice --list-domains[/] to see valid options."
        )
        sys.exit(1)

    projects_root: Path = ctx.obj["projects_root"]
    slug = slugify(slug) or slugify(name) or "practice-sandbox"
    db_path = project_db_path(projects_root, slug)
    project_dir = db_path.parent

    if project_dir.exists():
        should_overwrite = overwrite or Confirm.ask(
            f"Practice project '{slug}' already exists. Overwrite it?",
            default=False,
        )
        if not should_overwrite:
            console.print("[yellow]Cancelled.[/]")
            sys.exit(1)
        shutil.rmtree(project_dir)

    console.print(Panel(
        "[bold cyan]Polyphony Practice[/bold cyan]\n"
        "Creating an isolated sandbox project for guided training.",
        expand=False,
    ))

    conn = connect(db_path)
    try:
        project_id = _create_practice_project(
            conn,
            name=name,
            slug=slug,
            methodology=methodology,
            model_a=model_a,
            model_b=model_b,
            temperature=temperature,
        )

        codes: list[dict] = []
        if source_files:
            console.print(f"[bold]Importing {len(source_files)} file(s) into sandbox...[/]")
            import_result = import_documents(
                conn=conn,
                project_id=project_id,
                paths=list(source_files),
                segment_strategy=segment_by,
                project_dir=project_dir,
            )
            data_mode = "real-data"
        else:
            if topic:
                console.print(f"[bold]Generating {segments} LLM segments for topic:[/] {topic}")
                generated = generate_llm_data(
                    topic=topic,
                    n_segments=segments,
                    model=llm_model,
                    seed=seed,
                )
                data_mode = "llm-synthetic"
            else:
                console.print(
                    f"[bold]Generating {segments} offline template segments from domain:[/] {domain}"
                )
                generated = generate_template_data(
                    domain=domain,
                    n_segments=segments,
                    seed=seed,
                )
                data_mode = "template-synthetic"

            import_result = _import_generated_segments(
                conn,
                project_id=project_id,
                project_dir=project_dir,
                generated_segments=generated.get("segments", []),
            )
            codes = generated.get("codes", [])

        conn.execute(
            "UPDATE project SET config = ? WHERE id = ?",
            (json.dumps({"practice": True, "practice_data_mode": data_mode}, ensure_ascii=False), project_id),
        )
        conn.commit()
    finally:
        conn.close()

    if not no_open:
        write_project_marker(Path.cwd(), project_dir)

    console.print(
        f"\n[green]Practice environment ready:[/] "
        f"{import_result['documents_imported']} document(s), "
        f"{import_result['segments_created']} segment(s)."
    )
    if import_result["skipped"]:
        console.print(f"[yellow]Skipped {len(import_result['skipped'])} file(s).[/]")

    _print_suggested_codes(codes)

    console.print("\n[bold]Suggested workflow[/]")
    console.print(f"  1. polyphony --project {slug} project status")
    console.print(f"  2. polyphony --project {slug} codebook induce")
    console.print(f"  3. polyphony --project {slug} code run")
    console.print(f"  4. polyphony --project {slug} irr compute")
    console.print(f"  5. polyphony --project {slug} discuss flags")

    if not no_open:
        console.print("\n[dim].polyphony_project updated in this working directory.[/]")

